# Lab 10
### Daniel Mehta

In [8]:
#imports
import numpy as np
import random

---

## Setting Up the Environment

### Grid Environment

In [12]:
# grid parameters
grid_size = 5
start_pos = (0,0)
goal_pos = (4,4)

# Initializing the grid
grid = np.zeros((grid_size,grid_size), dtype=int)

In [16]:
# Marking the start and goal
grid[start_pos]=1 # 1 is the Start
grid[goal_pos]=2 # 2 is the Goal

In [18]:
# Randomly placeing 3 obstacles (obstacles are being represented by -1)
obstacles = set()
while len(obstacles) <3:
    pos = (random.randint(0,4), random.randint(0,4))
    if pos !=start_pos and pos != goal_pos and pos not in obstacles:
        obstacles.add(pos)
        grid[pos] = -1  # Obstacle

In [20]:
print("Grid:\n", grid)

Grid:
 [[ 1  0  0  0  0]
 [ 0  0  0 -1  0]
 [-1  0  0  0  0]
 [ 0  0  0  0 -1]
 [ 0  0  0  0  2]]
