# Lab 10
### Daniel Mehta

In [8]:
#imports
import numpy as np
import random

---

## Setting Up the Environment

### Grid Environment

In [12]:
# grid parameters
grid_size = 5
start_pos = (0,0)
goal_pos = (4,4)

# Initializing the grid
grid = np.zeros((grid_size,grid_size), dtype=int)

In [16]:
# Marking the start and goal
grid[start_pos]=1 # 1 is the Start
grid[goal_pos]=2 # 2 is the Goal

In [18]:
# Randomly placeing 3 obstacles (obstacles are being represented by -1)
obstacles = set()
while len(obstacles) <3:
    pos = (random.randint(0,4), random.randint(0,4))
    if pos !=start_pos and pos != goal_pos and pos not in obstacles:
        obstacles.add(pos)
        grid[pos] = -1  # Obstacle

In [22]:
print("Grid:\n", grid)

print("\nLegend:")
print("  0 = Empty")
print("  1 = Start")
print("  2 = Goal")
print(" -1 = Obstacle")

Grid:
 [[ 1  0  0  0  0]
 [ 0  0  0 -1  0]
 [-1  0  0  0  0]
 [ 0  0  0  0 -1]
 [ 0  0  0  0  2]]

Legend:
  0 = Empty
  1 = Start
  2 = Goal
 -1 = Obstacle


### Rewards

In [25]:
# Creating a reward matrix matching the grid
rewards = np.zeros((grid_size, grid_size),dtype=int)

In [27]:
# Assigning the rewards
for i in range(grid_size):
    for j in range(grid_size):
        if (i,j) == goal_pos:
            rewards[i,j] =10
        elif (i, j) in obstacles:
            rewards[i,j] = -10
        else:
            rewards[i,j] = 0

In [29]:
print("Reward Matrix:\n", rewards)

Reward Matrix:
 [[  0   0   0   0   0]
 [  0   0   0 -10   0]
 [-10   0   0   0   0]
 [  0   0   0   0 -10]
 [  0   0   0   0  10]]


### State Representation

In [34]:
def state_to_index(state):
    # Converts the grid state (i, j) to a single index
    return state[0]*grid_size+ state[1]

In [40]:
sample_state = (2,3)
print("State index for", sample_state, ":", state_to_index(sample_state))

State index for (2, 3) : 13


## Implementing Deep Q-Learning